### ISSUE TITLE
shortcut trigger an error in the console

### ISSUE THREAD

**Issue by srouquette** [ccampbell/sublime-goto-window#1]
here is the log:
    return self.run()
  File "GotoWindow in D:\apps\SublimeText\Data\Installed Packages\GotoWindow.sublime-package", line 9, in run
  File "GotoWindow in D:\apps\SublimeText\Data\Installed Packages\GotoWindow.sublime-package", line 91, in _get_folders
TypeError: startswith first arg must be str or a tuple of str, not NoneType

Windows 10 x64, Python 3.3, SublimeText 3
(python may be the problem here)

**Comment by aspyatkin** [comment]
I've run into the same issue on Windows computer.
It seems that on Windows [this call](https://github.com/ccampbell/sublime-goto-window/blob/master/GotoWindow.py#L88) just returns `None`, that's why calling `str.startswith` fails later on.

**UPD**. If you just comment lines 88, 91 and 92 out in `GotoWindow.py` file, plugin will work on Windows. Unfortunately, the menu is populated with the values of each folder attached to each project, and it's not convenient.
_E.g._ I'm working on two projects, each runs in its own Sublime Text window. Each project has multiple folders attached to it. When I open the menu, I see the list with all folders, but it's not what I expect it to contain. I would like to have a list with all windows names (or other identifiers) except current one. In the case mentioned above there should be only one item pointing to the other SublimeText window.
